{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "clmap",
    "version": "0.4.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "3gfd4cmxifgllfyndnm2ycb62m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "clmap-0.4.00.jar",
          "url": "clmap-0.4.00.jar",
          "size": 76082,
          "sha512": "6b4a6556cd2d735434709182edca52962685b7e4dfe3fa961d91affe61906460da08a5cc32683238d9c3ef4f05d05c7cfbb68c2458e5dd60b8b4b12a0f459e39",
          "sha256": "3dd1d6b6e7bdb9507e642e4089c7125fa3c60e8994ed8f6ba659dad4dc190ce2",
          "sha1": "7d18776c3f33102efee6b199e683c4573cce9ebe",
          "md5": "d31be129c3ea4ed51663f4d05091d291"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "0.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "0.4.00"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        }
      ],
      "files": [
        {
          "name": "clmap-0.4.00.jar",
          "url": "clmap-0.4.00.jar",
          "size": 76082,
          "sha512": "6b4a6556cd2d735434709182edca52962685b7e4dfe3fa961d91affe61906460da08a5cc32683238d9c3ef4f05d05c7cfbb68c2458e5dd60b8b4b12a0f459e39",
          "sha256": "3dd1d6b6e7bdb9507e642e4089c7125fa3c60e8994ed8f6ba659dad4dc190ce2",
          "sha1": "7d18776c3f33102efee6b199e683c4573cce9ebe",
          "md5": "d31be129c3ea4ed51663f4d05091d291"
        }
      ]
    }
  ]
}
