{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "clmap",
    "version": "0.4.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "7udpawlbv5g6dda565vewwnp7e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "clmap-0.4.00.jar",
          "url": "clmap-0.4.00.jar",
          "size": 74632,
          "sha512": "226c7799b13ce3ee4187513a981db59349b237cb4f71e1016f95e9756384852b0ea561f6724937ab48b6afbb4fa68d78c9109f80cebff0be9372a783a9b4d1c5",
          "sha256": "513e3568d0b1445d3250fa1626fccc7bd54aaf8a9d6b8dce831e9503af65403b",
          "sha1": "503d0b63de72431b29cad52297e975e60d3fd827",
          "md5": "a3ff6769750ef91ebd36f396d3756c38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "0.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "0.4.00"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        }
      ],
      "files": [
        {
          "name": "clmap-0.4.00.jar",
          "url": "clmap-0.4.00.jar",
          "size": 74632,
          "sha512": "226c7799b13ce3ee4187513a981db59349b237cb4f71e1016f95e9756384852b0ea561f6724937ab48b6afbb4fa68d78c9109f80cebff0be9372a783a9b4d1c5",
          "sha256": "513e3568d0b1445d3250fa1626fccc7bd54aaf8a9d6b8dce831e9503af65403b",
          "sha1": "503d0b63de72431b29cad52297e975e60d3fd827",
          "md5": "a3ff6769750ef91ebd36f396d3756c38"
        }
      ]
    }
  ]
}
