{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "tpac",
    "version": "1.1.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        }
      ],
      "files": [
        {
          "name": "tpac-1.1.00.jar",
          "url": "tpac-1.1.00.jar",
          "size": 172940,
          "sha512": "38edd439735e8a13612ca540312da02e5cecf65c8d081f6d7f054b6108da28ad92c7ec5b711db2269265e52f4ca7cef2d92b016447774d3e4a66d86b84f0ff54",
          "sha256": "40e7daaad64be6a2392df5032902088508674bea90c8263b0124f81cfadb981f",
          "sha1": "a085a4cc4f6f2094d6f65cc5c2024aa756b7e031",
          "md5": "796dcbb1d4353f71267eddc8f6efefc7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        }
      ],
      "files": [
        {
          "name": "tpac-1.1.00.jar",
          "url": "tpac-1.1.00.jar",
          "size": 172940,
          "sha512": "38edd439735e8a13612ca540312da02e5cecf65c8d081f6d7f054b6108da28ad92c7ec5b711db2269265e52f4ca7cef2d92b016447774d3e4a66d86b84f0ff54",
          "sha256": "40e7daaad64be6a2392df5032902088508674bea90c8263b0124f81cfadb981f",
          "sha1": "a085a4cc4f6f2094d6f65cc5c2024aa756b7e031",
          "md5": "796dcbb1d4353f71267eddc8f6efefc7"
        }
      ]
    }
  ]
}
