{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "tpac",
    "version": "1.1.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        }
      ],
      "files": [
        {
          "name": "tpac-1.1.00.jar",
          "url": "tpac-1.1.00.jar",
          "size": 172076,
          "sha512": "3d3b2e76dd1863df0452859fc9530bfc664358c8779540cd161350e0e69b3ed4cbea39a3e37de3c406d56a0bb24f210f7f9feeecb20e33d696a64d984dea921a",
          "sha256": "7583dc5fd713d3fab192c9309d41493b3bc8353290b4a887356090d9d3b80bff",
          "sha1": "e50ff969f04f7bffc32b993737e4d31bf4777372",
          "md5": "00ed9b18a9f0a99a4276a95e2c09431f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        }
      ],
      "files": [
        {
          "name": "tpac-1.1.00.jar",
          "url": "tpac-1.1.00.jar",
          "size": 172076,
          "sha512": "3d3b2e76dd1863df0452859fc9530bfc664358c8779540cd161350e0e69b3ed4cbea39a3e37de3c406d56a0bb24f210f7f9feeecb20e33d696a64d984dea921a",
          "sha256": "7583dc5fd713d3fab192c9309d41493b3bc8353290b4a887356090d9d3b80bff",
          "sha1": "e50ff969f04f7bffc32b993737e4d31bf4777372",
          "md5": "00ed9b18a9f0a99a4276a95e2c09431f"
        }
      ]
    }
  ]
}
