{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "tpac",
    "version": "1.1.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        }
      ],
      "files": [
        {
          "name": "tpac-1.1.00.jar",
          "url": "tpac-1.1.00.jar",
          "size": 172720,
          "sha512": "87abdfb7b8f76485546045eaab20563589c73c6f1a88e297a6515645ce5f141cc759e47e33cc9db3e76a8be5124e9d0c0eb7b0a4bad355bb0d37c947ef80c7b6",
          "sha256": "a92579ecac03986ea7bbb2842a2079ba9d950548b1f3165b56947ff3619d4640",
          "sha1": "d3db8b2de007e0e42c0065232740ca8e4b4e78a2",
          "md5": "d72970a638cdd5cc5e387b32e897d5df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        }
      ],
      "files": [
        {
          "name": "tpac-1.1.00.jar",
          "url": "tpac-1.1.00.jar",
          "size": 172720,
          "sha512": "87abdfb7b8f76485546045eaab20563589c73c6f1a88e297a6515645ce5f141cc759e47e33cc9db3e76a8be5124e9d0c0eb7b0a4bad355bb0d37c947ef80c7b6",
          "sha256": "a92579ecac03986ea7bbb2842a2079ba9d950548b1f3165b56947ff3619d4640",
          "sha1": "d3db8b2de007e0e42c0065232740ca8e4b4e78a2",
          "md5": "d72970a638cdd5cc5e387b32e897d5df"
        }
      ]
    }
  ]
}
