{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "yakumo",
    "version": "1.4.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "bltxt",
          "version": {
            "requires": "1.3.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "2.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "switem",
          "version": {
            "requires": "1.3.00"
          }
        }
      ],
      "files": [
        {
          "name": "yakumo-1.4.00.jar",
          "url": "yakumo-1.4.00.jar",
          "size": 99150,
          "sha512": "1f21cddf1f1d293e4339ab92502613af2f69bd351b25aac44d4d4230a36fccd42e051a01eeb771021066964724eb8afb3d28da0fce019a0bf710456ba730ce43",
          "sha256": "92c595f30dedf280ee2da39fe9382b010a769ad6eed543bf558341d895a12e06",
          "sha1": "58cb83359a743320ce4aed0dac8d6070b7a87ccd",
          "md5": "85bdcff75d9117ed0d620e039488bfe5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.codehaus.gpars",
          "module": "gpars",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "bltxt",
          "version": {
            "requires": "1.3.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "2.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "switem",
          "version": {
            "requires": "1.3.00"
          }
        }
      ],
      "files": [
        {
          "name": "yakumo-1.4.00.jar",
          "url": "yakumo-1.4.00.jar",
          "size": 99150,
          "sha512": "1f21cddf1f1d293e4339ab92502613af2f69bd351b25aac44d4d4230a36fccd42e051a01eeb771021066964724eb8afb3d28da0fce019a0bf710456ba730ce43",
          "sha256": "92c595f30dedf280ee2da39fe9382b010a769ad6eed543bf558341d895a12e06",
          "sha1": "58cb83359a743320ce4aed0dac8d6070b7a87ccd",
          "md5": "85bdcff75d9117ed0d620e039488bfe5"
        }
      ]
    }
  ]
}
