{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "yakumo",
    "version": "1.4.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "bltxt",
          "version": {
            "requires": "1.3.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "2.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "switem",
          "version": {
            "requires": "1.3.00"
          }
        }
      ],
      "files": [
        {
          "name": "yakumo-1.4.00.jar",
          "url": "yakumo-1.4.00.jar",
          "size": 99135,
          "sha512": "3f8e6249aedd4b99665911fe66c9dee3c3a7bf43dd4f28e9f77a277e815ee74618988f8178344ba90f7a553dd820bd9bb311491d47444c34b300d0142f5ab694",
          "sha256": "983fae33ca842b2dedafe5af6d82dd76f889f465f8b386b50aff15bfa312ccaa",
          "sha1": "873cbc8cd01fc78b3a8859eb78fff8616f37c2cb",
          "md5": "c1f6a3cc6b50e9b6a7c242bc518c437a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.codehaus.gpars",
          "module": "gpars",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "bltxt",
          "version": {
            "requires": "1.3.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "2.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "switem",
          "version": {
            "requires": "1.3.00"
          }
        }
      ],
      "files": [
        {
          "name": "yakumo-1.4.00.jar",
          "url": "yakumo-1.4.00.jar",
          "size": 99135,
          "sha512": "3f8e6249aedd4b99665911fe66c9dee3c3a7bf43dd4f28e9f77a277e815ee74618988f8178344ba90f7a553dd820bd9bb311491d47444c34b300d0142f5ab694",
          "sha256": "983fae33ca842b2dedafe5af6d82dd76f889f465f8b386b50aff15bfa312ccaa",
          "sha1": "873cbc8cd01fc78b3a8859eb78fff8616f37c2cb",
          "md5": "c1f6a3cc6b50e9b6a7c242bc518c437a"
        }
      ]
    }
  ]
}
