{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "yakumo",
    "version": "1.4.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "bltxt",
          "version": {
            "requires": "1.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "2.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "switem",
          "version": {
            "requires": "1.3.00"
          }
        }
      ],
      "files": [
        {
          "name": "yakumo-1.4.00.jar",
          "url": "yakumo-1.4.00.jar",
          "size": 92729,
          "sha512": "0c8a00b3d0160f2c7b4c14f8760250b121b67db69014aab48a287dda3bc2f608c5224a7fd8fe362a7e8bd7e10e28bfe3cbc147f0479ef5a9cb4089e69336e48a",
          "sha256": "ea1626822a5902f7b11d57ef1a2b84593ba895fc3147bfde2da0b8e138bce72f",
          "sha1": "d6d0376a434782a1fa8a0277b29301e1a95571a3",
          "md5": "82be1a4af66667bbea833c6e27609b67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.codehaus.gpars",
          "module": "gpars",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "bltxt",
          "version": {
            "requires": "1.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "2.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "switem",
          "version": {
            "requires": "1.3.00"
          }
        }
      ],
      "files": [
        {
          "name": "yakumo-1.4.00.jar",
          "url": "yakumo-1.4.00.jar",
          "size": 92729,
          "sha512": "0c8a00b3d0160f2c7b4c14f8760250b121b67db69014aab48a287dda3bc2f608c5224a7fd8fe362a7e8bd7e10e28bfe3cbc147f0479ef5a9cb4089e69336e48a",
          "sha256": "ea1626822a5902f7b11d57ef1a2b84593ba895fc3147bfde2da0b8e138bce72f",
          "sha1": "d6d0376a434782a1fa8a0277b29301e1a95571a3",
          "md5": "82be1a4af66667bbea833c6e27609b67"
        }
      ]
    }
  ]
}
