{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "gonfig",
    "version": "0.2.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "23n3c7xw75cephikxpzlwug4ga"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gonfig-0.2.00.jar",
          "url": "gonfig-0.2.00.jar",
          "size": 16929,
          "sha512": "47c84c7c69f9aeafc636fe3db038e0faaf7004d8020fcf6659e47b483c3716c517fac5b137ed0301c240e5c04e097bf6ec94cb4d3c3bd851597cf624bebf18e6",
          "sha256": "a2a6c0ef9a83cbcab5de356097960362d39a10449999d807fec32dd980fdd680",
          "sha1": "3f052dbc33c19621ca60571b54ce6c72bc125b21",
          "md5": "ef03b56aa6cb40dcfa588f0766ebaff2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        }
      ],
      "files": [
        {
          "name": "gonfig-0.2.00.jar",
          "url": "gonfig-0.2.00.jar",
          "size": 16929,
          "sha512": "47c84c7c69f9aeafc636fe3db038e0faaf7004d8020fcf6659e47b483c3716c517fac5b137ed0301c240e5c04e097bf6ec94cb4d3c3bd851597cf624bebf18e6",
          "sha256": "a2a6c0ef9a83cbcab5de356097960362d39a10449999d807fec32dd980fdd680",
          "sha1": "3f052dbc33c19621ca60571b54ce6c72bc125b21",
          "md5": "ef03b56aa6cb40dcfa588f0766ebaff2"
        }
      ]
    }
  ]
}
