{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "gonfig",
    "version": "0.2.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "adk32v234redjn5wrakni4un6m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gonfig-0.2.00.jar",
          "url": "gonfig-0.2.00.jar",
          "size": 16738,
          "sha512": "0a326d3bb99f14a2a9ab13e9f2f103dc563e108931c740b7890d90f70c1f9bf32e90afc1fa53dc79a0a3a8bfeb6b5b690070c9aa76290be342909dcdf74656d7",
          "sha256": "c2df01bfffc11d13e80361f4b0d2f8bb9a2a76de647c5a723071f4f51682e2ab",
          "sha1": "99957ec7ff37b82f0f4cdec4877f5349ddafbae6",
          "md5": "9fb44c05cddb6302bb10f3dd1c741feb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        }
      ],
      "files": [
        {
          "name": "gonfig-0.2.00.jar",
          "url": "gonfig-0.2.00.jar",
          "size": 16738,
          "sha512": "0a326d3bb99f14a2a9ab13e9f2f103dc563e108931c740b7890d90f70c1f9bf32e90afc1fa53dc79a0a3a8bfeb6b5b690070c9aa76290be342909dcdf74656d7",
          "sha256": "c2df01bfffc11d13e80361f4b0d2f8bb9a2a76de647c5a723071f4f51682e2ab",
          "sha1": "99957ec7ff37b82f0f4cdec4877f5349ddafbae6",
          "md5": "9fb44c05cddb6302bb10f3dd1c741feb"
        }
      ]
    }
  ]
}
