{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "gonfig",
    "version": "0.2.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "coonjjy26fcn5ir2feudadgaee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gonfig-0.2.00.jar",
          "url": "gonfig-0.2.00.jar",
          "size": 16236,
          "sha512": "66998cc234abd7f79ce9cf2f849e630859e7c5ed408ebb6624c33244487229c3f81c71faf8a725a8097b7fa1181ad31ed1189127f687c5b4f0ba8b26b6ea7247",
          "sha256": "beb26297bc2ad17f77fd57f607a71ee5676921552267730fa0bdf87cd38230b6",
          "sha1": "f111012e86b7ce5e89df0c67c3c961081905152a",
          "md5": "e7a61b5124d9a06a9baa148f7c6ba21c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        }
      ],
      "files": [
        {
          "name": "gonfig-0.2.00.jar",
          "url": "gonfig-0.2.00.jar",
          "size": 16236,
          "sha512": "66998cc234abd7f79ce9cf2f849e630859e7c5ed408ebb6624c33244487229c3f81c71faf8a725a8097b7fa1181ad31ed1189127f687c5b4f0ba8b26b6ea7247",
          "sha256": "beb26297bc2ad17f77fd57f607a71ee5676921552267730fa0bdf87cd38230b6",
          "sha1": "f111012e86b7ce5e89df0c67c3c961081905152a",
          "md5": "e7a61b5124d9a06a9baa148f7c6ba21c"
        }
      ]
    }
  ]
}
