{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "switem",
    "version": "0.1.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "j5phwf4lxfh5fgg4pgys5m3u5i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "switem-0.1.00.jar",
          "url": "switem-0.1.00.jar",
          "size": 103862,
          "sha512": "a5199b0c1d81d2929d2be13f7982b7b9b916fccec465734d2adc099bf053956f32c2f35fee9c30f521c3776f1acac58588260dee8df0d2ac08c49e6a4d981f63",
          "sha256": "1a1492b7602b959d983a6e70ed7a59b836c90b5c16038286aa7622cbd43f1bec",
          "sha1": "27ad4211502816bf4a619a289d9a7324c2d9c6f3",
          "md5": "433750f27efbb6947bfbe3b902b01ad2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "0.4.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "0.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "0.4.00"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        }
      ],
      "files": [
        {
          "name": "switem-0.1.00.jar",
          "url": "switem-0.1.00.jar",
          "size": 103862,
          "sha512": "a5199b0c1d81d2929d2be13f7982b7b9b916fccec465734d2adc099bf053956f32c2f35fee9c30f521c3776f1acac58588260dee8df0d2ac08c49e6a4d981f63",
          "sha256": "1a1492b7602b959d983a6e70ed7a59b836c90b5c16038286aa7622cbd43f1bec",
          "sha1": "27ad4211502816bf4a619a289d9a7324c2d9c6f3",
          "md5": "433750f27efbb6947bfbe3b902b01ad2"
        }
      ]
    }
  ]
}
