{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "switem",
    "version": "0.1.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "fmz4w7wfsjdwlmejegmw7ozr7m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "switem-0.1.00.jar",
          "url": "switem-0.1.00.jar",
          "size": 103762,
          "sha512": "44f892d6cffe6e42dc963e244bb9b85c1170ab3d559882ba3ea50ee467986ec45ed70bdc9578c7d4cfb118cf114c95261e6b63f32c9017f4fd055cdd54372b51",
          "sha256": "c0d6bc011aa41085f0589d7cfb6788db138609b6585f0d7e26915a40c6ccd0a4",
          "sha1": "9319723f6e1e574628427a75550debc87f6f31c8",
          "md5": "1287d63b22405bdfbee4be9a726d69da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "0.4.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "0.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "0.4.00"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        }
      ],
      "files": [
        {
          "name": "switem-0.1.00.jar",
          "url": "switem-0.1.00.jar",
          "size": 103762,
          "sha512": "44f892d6cffe6e42dc963e244bb9b85c1170ab3d559882ba3ea50ee467986ec45ed70bdc9578c7d4cfb118cf114c95261e6b63f32c9017f4fd055cdd54372b51",
          "sha256": "c0d6bc011aa41085f0589d7cfb6788db138609b6585f0d7e26915a40c6ccd0a4",
          "sha1": "9319723f6e1e574628427a75550debc87f6f31c8",
          "md5": "1287d63b22405bdfbee4be9a726d69da"
        }
      ]
    }
  ]
}
