{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "switem",
    "version": "0.1.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "yptss6ht4jfaphxy66yic5glhi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "switem-0.1.00.jar",
          "url": "switem-0.1.00.jar",
          "size": 105425,
          "sha512": "96db54c5598b522dbda8e98e76db76d37da0891ae58778b844b3f6e34459c6c5f40864158ca1ea5d72a2a8ac6ca7866d31038512c5cb42fbe2e7982dcb5e9609",
          "sha256": "9dfb95045cd6e94c9dfc6ae0b058bb31b4e23f7028b178c974028bcc890f93fd",
          "sha1": "e4ef6371f4084498926128006dd3d2c3da3bb48a",
          "md5": "aef05bdeab62563c1f171c88c6911305"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "0.4.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "0.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "0.4.00"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        }
      ],
      "files": [
        {
          "name": "switem-0.1.00.jar",
          "url": "switem-0.1.00.jar",
          "size": 105425,
          "sha512": "96db54c5598b522dbda8e98e76db76d37da0891ae58778b844b3f6e34459c6c5f40864158ca1ea5d72a2a8ac6ca7866d31038512c5cb42fbe2e7982dcb5e9609",
          "sha256": "9dfb95045cd6e94c9dfc6ae0b058bb31b4e23f7028b178c974028bcc890f93fd",
          "sha1": "e4ef6371f4084498926128006dd3d2c3da3bb48a",
          "md5": "aef05bdeab62563c1f171c88c6911305"
        }
      ]
    }
  ]
}
