{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "yakumo",
    "version": "1.2.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "bltxt",
          "version": {
            "requires": "1.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "1.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "switem",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "yakumo-1.2.00.jar",
          "url": "yakumo-1.2.00.jar",
          "size": 79760,
          "sha512": "d1ccf4b4fd6977b46c6867a783d78313d946d24c4091ed83201857f58ca9288c062ffa5af569324ce6eb3febab93cb42b10b820fee13c99e181a6411b26bc3d0",
          "sha256": "d16d531ab820331e02e1f7f3c5e7272b0c2af8a6bf1853782029ca211e1689db",
          "sha1": "5b4f5da5583265aa0156f4b92eff1cf4e0a73047",
          "md5": "9e60aa1719b3c3402d80e54fba186e49"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.codehaus.gpars",
          "module": "gpars",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "bltxt",
          "version": {
            "requires": "1.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "1.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "switem",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "yakumo-1.2.00.jar",
          "url": "yakumo-1.2.00.jar",
          "size": 79760,
          "sha512": "d1ccf4b4fd6977b46c6867a783d78313d946d24c4091ed83201857f58ca9288c062ffa5af569324ce6eb3febab93cb42b10b820fee13c99e181a6411b26bc3d0",
          "sha256": "d16d531ab820331e02e1f7f3c5e7272b0c2af8a6bf1853782029ca211e1689db",
          "sha1": "5b4f5da5583265aa0156f4b92eff1cf4e0a73047",
          "md5": "9e60aa1719b3c3402d80e54fba186e49"
        }
      ]
    }
  ]
}
