{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "yakumo",
    "version": "1.2.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "bltxt",
          "version": {
            "requires": "1.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "1.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "switem",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "yakumo-1.2.00.jar",
          "url": "yakumo-1.2.00.jar",
          "size": 87137,
          "sha512": "cd5ba2043f9220cb5c03b242d80ec86b428aa66d448567e17af6f81955a2a51eaa20c69c1e92f393f4af564301ac5fc704e4b3b62aa10af4e9fcd9f705866c4c",
          "sha256": "0d1cddc6bcbcfc81f9b3e8dabafb79ae7573d2bc4ca0b006e2c4350523def225",
          "sha1": "1843c7c0c892cef4445043b038373460302fef4c",
          "md5": "c893be59c1077e3a56fe290eae603dae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.codehaus.gpars",
          "module": "gpars",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "bltxt",
          "version": {
            "requires": "1.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "1.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "switem",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "yakumo-1.2.00.jar",
          "url": "yakumo-1.2.00.jar",
          "size": 87137,
          "sha512": "cd5ba2043f9220cb5c03b242d80ec86b428aa66d448567e17af6f81955a2a51eaa20c69c1e92f393f4af564301ac5fc704e4b3b62aa10af4e9fcd9f705866c4c",
          "sha256": "0d1cddc6bcbcfc81f9b3e8dabafb79ae7573d2bc4ca0b006e2c4350523def225",
          "sha1": "1843c7c0c892cef4445043b038373460302fef4c",
          "md5": "c893be59c1077e3a56fe290eae603dae"
        }
      ]
    }
  ]
}
