{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "yakumo",
    "version": "1.2.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "bltxt",
          "version": {
            "requires": "1.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "1.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "switem",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "yakumo-1.2.00.jar",
          "url": "yakumo-1.2.00.jar",
          "size": 87113,
          "sha512": "933038cd2d90386774f6651ec945fe46e7e5f93bf40292966b59694f687b4f9276fa3dbd1e274a23b89ff58fc7791a18b220446eab3b36b39f14ab9be25759ab",
          "sha256": "03e2728dc2e3c01dfc17c21363d9685c9d145e9f447a6feb1f366d8b7d0cd0b5",
          "sha1": "b26b4130782a4900a562c1bc8165520c7f985616",
          "md5": "d1a5615a250624426f01988cf3fefbc1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.codehaus.gpars",
          "module": "gpars",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "bltxt",
          "version": {
            "requires": "1.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "1.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "switem",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "yakumo-1.2.00.jar",
          "url": "yakumo-1.2.00.jar",
          "size": 87113,
          "sha512": "933038cd2d90386774f6651ec945fe46e7e5f93bf40292966b59694f687b4f9276fa3dbd1e274a23b89ff58fc7791a18b220446eab3b36b39f14ab9be25759ab",
          "sha256": "03e2728dc2e3c01dfc17c21363d9685c9d145e9f447a6feb1f366d8b7d0cd0b5",
          "sha1": "b26b4130782a4900a562c1bc8165520c7f985616",
          "md5": "d1a5615a250624426f01988cf3fefbc1"
        }
      ]
    }
  ]
}
