{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "gonfig",
    "version": "1.1.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gonfig-1.1.00.jar",
          "url": "gonfig-1.1.00.jar",
          "size": 16713,
          "sha512": "f156df6a3f070a0d30bb132a08cb54dfbdfd38d08ce6a7d00edbd1851f77907117c016e7aca69dbb37e8360bac3721f15fd596b068bbb135baff53a8755285e2",
          "sha256": "1294de2f86a53a964113b23150832010f6079581ae8422ea83cdf60c83326238",
          "sha1": "ef915f52222788f461b11aa83791075b61848d1b",
          "md5": "2f6b495c9b44fd08621a3d2198b0d3c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "gonfig-1.1.00.jar",
          "url": "gonfig-1.1.00.jar",
          "size": 16713,
          "sha512": "f156df6a3f070a0d30bb132a08cb54dfbdfd38d08ce6a7d00edbd1851f77907117c016e7aca69dbb37e8360bac3721f15fd596b068bbb135baff53a8755285e2",
          "sha256": "1294de2f86a53a964113b23150832010f6079581ae8422ea83cdf60c83326238",
          "sha1": "ef915f52222788f461b11aa83791075b61848d1b",
          "md5": "2f6b495c9b44fd08621a3d2198b0d3c8"
        }
      ]
    }
  ]
}
