{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "clmap",
    "version": "2.1.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "clmap-2.1.00.jar",
          "url": "clmap-2.1.00.jar",
          "size": 78003,
          "sha512": "d52bb11d9976e40a9bdc405aeda529ccbf48020cb4f274c52199a8b479338e8f3876736631a012182119bf4d678066c38c9148c9e648416df24ef31d5dd5e18b",
          "sha256": "09372a583a74a74d892ca282b3a1a08b54669e38dae9220a1b8d50f846c4f605",
          "sha1": "9ce7369fe42e47d13de25ccacbb1f74926bc8111",
          "md5": "293ebc49613b13dadf5cb22a4ec4136c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "clmap-2.1.00.jar",
          "url": "clmap-2.1.00.jar",
          "size": 78003,
          "sha512": "d52bb11d9976e40a9bdc405aeda529ccbf48020cb4f274c52199a8b479338e8f3876736631a012182119bf4d678066c38c9148c9e648416df24ef31d5dd5e18b",
          "sha256": "09372a583a74a74d892ca282b3a1a08b54669e38dae9220a1b8d50f846c4f605",
          "sha1": "9ce7369fe42e47d13de25ccacbb1f74926bc8111",
          "md5": "293ebc49613b13dadf5cb22a4ec4136c"
        }
      ]
    }
  ]
}
