{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "clmap",
    "version": "2.1.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "clmap-2.1.00.jar",
          "url": "clmap-2.1.00.jar",
          "size": 78077,
          "sha512": "fd04d26777fbdd02c0a8e6eb11b93ead1d29c27dd3a13014140ea5d854cd46945e6a7cca37a559fb530210f82ade827acd35a21b49b5e1722b23434fc55c48d3",
          "sha256": "82f2a9d0df601828c8fae79b608bc5558912ed9c2c4e885074911e720de1b3b3",
          "sha1": "943017464a6f457f111a0cc039eaed5b5b0a6b67",
          "md5": "f2d573c52417460acef3047bb0c2265f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "clmap-2.1.00.jar",
          "url": "clmap-2.1.00.jar",
          "size": 78077,
          "sha512": "fd04d26777fbdd02c0a8e6eb11b93ead1d29c27dd3a13014140ea5d854cd46945e6a7cca37a559fb530210f82ade827acd35a21b49b5e1722b23434fc55c48d3",
          "sha256": "82f2a9d0df601828c8fae79b608bc5558912ed9c2c4e885074911e720de1b3b3",
          "sha1": "943017464a6f457f111a0cc039eaed5b5b0a6b67",
          "md5": "f2d573c52417460acef3047bb0c2265f"
        }
      ]
    }
  ]
}
