{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "tpac",
    "version": "0.4.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "hwteawa7v5hnfdeg3n6tma65ei"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tpac-0.4.00.jar",
          "url": "tpac-0.4.00.jar",
          "size": 176089,
          "sha512": "829f8bde14efeb7613e2c4ad8792032d1748525091a4f77be962afe9d652449fe710da57f8c2d0fbc29a7320faea32f9f348e97e253f8efc0deee7c11a1913a4",
          "sha256": "3628261234c45fdd792a06fe87a38eebfc96b36d3ddff5bf6841de57fa4189e0",
          "sha1": "68749b9f9a49b4f942148a1ac0cc902087970b91",
          "md5": "fd3736b09157111dfe56f6ea0057e546"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "0.2.00"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        }
      ],
      "files": [
        {
          "name": "tpac-0.4.00.jar",
          "url": "tpac-0.4.00.jar",
          "size": 176089,
          "sha512": "829f8bde14efeb7613e2c4ad8792032d1748525091a4f77be962afe9d652449fe710da57f8c2d0fbc29a7320faea32f9f348e97e253f8efc0deee7c11a1913a4",
          "sha256": "3628261234c45fdd792a06fe87a38eebfc96b36d3ddff5bf6841de57fa4189e0",
          "sha1": "68749b9f9a49b4f942148a1ac0cc902087970b91",
          "md5": "fd3736b09157111dfe56f6ea0057e546"
        }
      ]
    }
  ]
}
