{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "clmap",
    "version": "1.2.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "clmap-1.2.00.jar",
          "url": "clmap-1.2.00.jar",
          "size": 79914,
          "sha512": "23ee4742d880164911ec36f0125d4d741d45bcb15efd039c4f4305a97fb0cf5bfdde8d7482e516fee662d135f14022d1d3271ca4e95e603eb1fbaf44fd186026",
          "sha256": "11479d511c3ef5c27696b806ae890b9efa600942a348b82e9553e362177c151c",
          "sha1": "f14721a1f2414303a342ebf24b76c0a2141cfd2e",
          "md5": "678ca76dce2b9dc5c91eea1ba695fe6c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "clmap-1.2.00.jar",
          "url": "clmap-1.2.00.jar",
          "size": 79914,
          "sha512": "23ee4742d880164911ec36f0125d4d741d45bcb15efd039c4f4305a97fb0cf5bfdde8d7482e516fee662d135f14022d1d3271ca4e95e603eb1fbaf44fd186026",
          "sha256": "11479d511c3ef5c27696b806ae890b9efa600942a348b82e9553e362177c151c",
          "sha1": "f14721a1f2414303a342ebf24b76c0a2141cfd2e",
          "md5": "678ca76dce2b9dc5c91eea1ba695fe6c"
        }
      ]
    }
  ]
}
