{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "clmap",
    "version": "1.2.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "clmap-1.2.00.jar",
          "url": "clmap-1.2.00.jar",
          "size": 79906,
          "sha512": "5ce15b1ee1aa99d4b4f285526018b9ecf071846d55f463a36ee92e79939583a02f463752af281fadde64b35144db7178157bc1092f37f6582138bc46f839670c",
          "sha256": "b53030fa9d31333a558c69b1dd5ee2bd7b1a620513b2e36f074dcaf6a5ed9257",
          "sha1": "53e73a1dbe3f1806f78c2bd85ba86f3395a7d121",
          "md5": "017637f619e8dd4406387ef860277e87"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "clmap-1.2.00.jar",
          "url": "clmap-1.2.00.jar",
          "size": 79906,
          "sha512": "5ce15b1ee1aa99d4b4f285526018b9ecf071846d55f463a36ee92e79939583a02f463752af281fadde64b35144db7178157bc1092f37f6582138bc46f839670c",
          "sha256": "b53030fa9d31333a558c69b1dd5ee2bd7b1a620513b2e36f074dcaf6a5ed9257",
          "sha1": "53e73a1dbe3f1806f78c2bd85ba86f3395a7d121",
          "md5": "017637f619e8dd4406387ef860277e87"
        }
      ]
    }
  ]
}
