{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "clmap",
    "version": "1.2.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "clmap-1.2.00.jar",
          "url": "clmap-1.2.00.jar",
          "size": 78392,
          "sha512": "44edfabb6441a6d8058b24095912bb091d269373b08a6348f77b5afb7ea6e5183c9f812b0a3cbebc746365333d20b17deb7f2f17612fa70026fdc9963c0e5bca",
          "sha256": "d70f84b7ea966c8652e09bc707539946e0456f839bcde28db932a218c7243ed6",
          "sha1": "6d5a08faf940af615267b9dbb23fe5a47f43854a",
          "md5": "809cc8a1deca5ff972bddc36234bf048"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "clmap-1.2.00.jar",
          "url": "clmap-1.2.00.jar",
          "size": 78392,
          "sha512": "44edfabb6441a6d8058b24095912bb091d269373b08a6348f77b5afb7ea6e5183c9f812b0a3cbebc746365333d20b17deb7f2f17612fa70026fdc9963c0e5bca",
          "sha256": "d70f84b7ea966c8652e09bc707539946e0456f839bcde28db932a218c7243ed6",
          "sha1": "6d5a08faf940af615267b9dbb23fe5a47f43854a",
          "md5": "809cc8a1deca5ff972bddc36234bf048"
        }
      ]
    }
  ]
}
