{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "yakumo",
    "version": "1.3.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "bltxt",
          "version": {
            "requires": "1.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "2.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "switem",
          "version": {
            "requires": "1.3.00"
          }
        }
      ],
      "files": [
        {
          "name": "yakumo-1.3.00.jar",
          "url": "yakumo-1.3.00.jar",
          "size": 90658,
          "sha512": "2a8be648d79fd40a13b06239f8d6039e861399f5be6a63229c5387e8ac69726f6177b596b99f5b19357b91c1c5a26640766290e0fd9d0ea28ab5e60b942f9664",
          "sha256": "65f4335e5aa8f5c99715a941f8ab7cd887e058e56627433de52d5e8a35534db9",
          "sha1": "b1870c6b4140cc6d4824afff61500d3296cbb2c6",
          "md5": "26946c320bdaaeed8ae8e4dc8508e379"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.codehaus.gpars",
          "module": "gpars",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "bltxt",
          "version": {
            "requires": "1.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "2.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "switem",
          "version": {
            "requires": "1.3.00"
          }
        }
      ],
      "files": [
        {
          "name": "yakumo-1.3.00.jar",
          "url": "yakumo-1.3.00.jar",
          "size": 90658,
          "sha512": "2a8be648d79fd40a13b06239f8d6039e861399f5be6a63229c5387e8ac69726f6177b596b99f5b19357b91c1c5a26640766290e0fd9d0ea28ab5e60b942f9664",
          "sha256": "65f4335e5aa8f5c99715a941f8ab7cd887e058e56627433de52d5e8a35534db9",
          "sha1": "b1870c6b4140cc6d4824afff61500d3296cbb2c6",
          "md5": "26946c320bdaaeed8ae8e4dc8508e379"
        }
      ]
    }
  ]
}
