{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "tpac",
    "version": "1.2.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        }
      ],
      "files": [
        {
          "name": "tpac-1.2.00.jar",
          "url": "tpac-1.2.00.jar",
          "size": 185057,
          "sha512": "ab8598a4acaadb50368cd5d3837fc5d1d7a34d2c8aa628f8406f196bd49c4908ed779cbd8a8e6a57937dfe9f27bc12d2954e8cdf262d68f2a8e4a449c9f36bcd",
          "sha256": "ce6bdf8e46ac69fedc94fc3ca814154f6123bb8e4b92b7808b76f47d8e684cb4",
          "sha1": "a3c3497efb028b92c54409f08483fd2a8d275a20",
          "md5": "714b276341fac2ec93bcc0e8decb1de2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        }
      ],
      "files": [
        {
          "name": "tpac-1.2.00.jar",
          "url": "tpac-1.2.00.jar",
          "size": 185057,
          "sha512": "ab8598a4acaadb50368cd5d3837fc5d1d7a34d2c8aa628f8406f196bd49c4908ed779cbd8a8e6a57937dfe9f27bc12d2954e8cdf262d68f2a8e4a449c9f36bcd",
          "sha256": "ce6bdf8e46ac69fedc94fc3ca814154f6123bb8e4b92b7808b76f47d8e684cb4",
          "sha1": "a3c3497efb028b92c54409f08483fd2a8d275a20",
          "md5": "714b276341fac2ec93bcc0e8decb1de2"
        }
      ]
    }
  ]
}
