{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "tpac",
    "version": "1.2.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        }
      ],
      "files": [
        {
          "name": "tpac-1.2.00.jar",
          "url": "tpac-1.2.00.jar",
          "size": 182806,
          "sha512": "f776ad1899e284c3f94f25aea44bb70ba588611b4895198b5eab558739b262448dd5d319d86ba58bd6c4c4c405342787859f46374f863b675bc0d0cdaa28c679",
          "sha256": "5f6cefe5477bc8f24bc545915ed9b5e5ffe89b5b885e7214945ce65032d8d76b",
          "sha1": "5036729239bc669fdedbfb043b4205bb4a304d2a",
          "md5": "97df63932f33147bbd02cdc6fce948ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        }
      ],
      "files": [
        {
          "name": "tpac-1.2.00.jar",
          "url": "tpac-1.2.00.jar",
          "size": 182806,
          "sha512": "f776ad1899e284c3f94f25aea44bb70ba588611b4895198b5eab558739b262448dd5d319d86ba58bd6c4c4c405342787859f46374f863b675bc0d0cdaa28c679",
          "sha256": "5f6cefe5477bc8f24bc545915ed9b5e5ffe89b5b885e7214945ce65032d8d76b",
          "sha1": "5036729239bc669fdedbfb043b4205bb4a304d2a",
          "md5": "97df63932f33147bbd02cdc6fce948ad"
        }
      ]
    }
  ]
}
