{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "gonfig",
    "version": "0.2.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "bbwtglbfzfhfrfdhz4kamghfd4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gonfig-0.2.00.jar",
          "url": "gonfig-0.2.00.jar",
          "size": 16929,
          "sha512": "9c02e66df3dfde88159157a7c0007a52c9496b284d04b3cfca19efccaefd3a99689b9173a03413b0f02719c0a04bab3320151af2d555d7e1450de80a34c55781",
          "sha256": "ba3287af1c952b07283f4eba70f75b19f32b2a2773edd8dd93de2e58f2336003",
          "sha1": "d031b9aaa16b7143fe0511e6d69f70d8d0fa1126",
          "md5": "03614e15dbb00ced3b17e1a2b305b0a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        }
      ],
      "files": [
        {
          "name": "gonfig-0.2.00.jar",
          "url": "gonfig-0.2.00.jar",
          "size": 16929,
          "sha512": "9c02e66df3dfde88159157a7c0007a52c9496b284d04b3cfca19efccaefd3a99689b9173a03413b0f02719c0a04bab3320151af2d555d7e1450de80a34c55781",
          "sha256": "ba3287af1c952b07283f4eba70f75b19f32b2a2773edd8dd93de2e58f2336003",
          "sha1": "d031b9aaa16b7143fe0511e6d69f70d8d0fa1126",
          "md5": "03614e15dbb00ced3b17e1a2b305b0a8"
        }
      ]
    }
  ]
}
