{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "clmap",
    "version": "1.1.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.1.00"
          }
        }
      ],
      "files": [
        {
          "name": "clmap-1.1.00.jar",
          "url": "clmap-1.1.00.jar",
          "size": 74323,
          "sha512": "54478448e8a92032045d173d085d9bf5a85d92d00efb72b8d4f729740e69442b12bfb88bb72230a951b5b5900810d27dc07b7702d96c2815e9e744a838de30d0",
          "sha256": "b41a42f2f4bff216296e29ae0cf56ac92e91f9088504e11fb2a0cf00b88bf2d1",
          "sha1": "50660475e1dfae91f289ef4acbd490121ba612ee",
          "md5": "c50dac144cc40188b965eb2bfad0043b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.1.00"
          }
        }
      ],
      "files": [
        {
          "name": "clmap-1.1.00.jar",
          "url": "clmap-1.1.00.jar",
          "size": 74323,
          "sha512": "54478448e8a92032045d173d085d9bf5a85d92d00efb72b8d4f729740e69442b12bfb88bb72230a951b5b5900810d27dc07b7702d96c2815e9e744a838de30d0",
          "sha256": "b41a42f2f4bff216296e29ae0cf56ac92e91f9088504e11fb2a0cf00b88bf2d1",
          "sha1": "50660475e1dfae91f289ef4acbd490121ba612ee",
          "md5": "c50dac144cc40188b965eb2bfad0043b"
        }
      ]
    }
  ]
}
