{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "clmap",
    "version": "1.1.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.1.00"
          }
        }
      ],
      "files": [
        {
          "name": "clmap-1.1.00.jar",
          "url": "clmap-1.1.00.jar",
          "size": 73886,
          "sha512": "02ff75a379d50d33f4fb54b2523ff48f9a1539ff86878319f3167750186aa39c399c1a72edd23025a08f209343ca3d8c1807c745cc76a1a6865a97c234a37fd2",
          "sha256": "fd564c7be2cd7d16229c8122dd5187e9e3631bacf66471b88cf115326af8dfbe",
          "sha1": "afbb1aa6e5d3013ef9eb2a04cdef63057dc59228",
          "md5": "25130671c67f6591fd824b149ad1484c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.1.00"
          }
        }
      ],
      "files": [
        {
          "name": "clmap-1.1.00.jar",
          "url": "clmap-1.1.00.jar",
          "size": 73886,
          "sha512": "02ff75a379d50d33f4fb54b2523ff48f9a1539ff86878319f3167750186aa39c399c1a72edd23025a08f209343ca3d8c1807c745cc76a1a6865a97c234a37fd2",
          "sha256": "fd564c7be2cd7d16229c8122dd5187e9e3631bacf66471b88cf115326af8dfbe",
          "sha1": "afbb1aa6e5d3013ef9eb2a04cdef63057dc59228",
          "md5": "25130671c67f6591fd824b149ad1484c"
        }
      ]
    }
  ]
}
