{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "clmap",
    "version": "1.1.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.1.00"
          }
        }
      ],
      "files": [
        {
          "name": "clmap-1.1.00.jar",
          "url": "clmap-1.1.00.jar",
          "size": 74142,
          "sha512": "d23fb8efaf57660a6ddfe322ac6c0b46afb4a5babb7cc15fa5f34ff0a5e5234f424ea5b056662ba5a6dc2f07260481c859e24d27bb1b4ed2deb9cf78f081be49",
          "sha256": "d402d400e4ecb63eae53759b37aea183dafc0bfe00f4f72507cc76ee48756c4a",
          "sha1": "c3fec4987de8898b0fde01c9ffd05d000ae6af3a",
          "md5": "51dd8eb226fbe94a57e71f3464d0f367"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.1.00"
          }
        }
      ],
      "files": [
        {
          "name": "clmap-1.1.00.jar",
          "url": "clmap-1.1.00.jar",
          "size": 74142,
          "sha512": "d23fb8efaf57660a6ddfe322ac6c0b46afb4a5babb7cc15fa5f34ff0a5e5234f424ea5b056662ba5a6dc2f07260481c859e24d27bb1b4ed2deb9cf78f081be49",
          "sha256": "d402d400e4ecb63eae53759b37aea183dafc0bfe00f4f72507cc76ee48756c4a",
          "sha1": "c3fec4987de8898b0fde01c9ffd05d000ae6af3a",
          "md5": "51dd8eb226fbe94a57e71f3464d0f367"
        }
      ]
    }
  ]
}
