{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "tpac",
    "version": "0.4.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "d4kkwb4eiza3poovlfm3zbbwha"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tpac-0.4.00.jar",
          "url": "tpac-0.4.00.jar",
          "size": 174673,
          "sha512": "64f5a5c638fd61acac78ca086d687a8b192a54dbd51735cf9289eb3c4a843dae8616132304773d52b1eddedb16ac905b50bf229412a132309415034edecba2c0",
          "sha256": "09e09a4ed987561e50fbb5fb6f0591ea950d51691bdeeb844fe15524e09b7163",
          "sha1": "a53d05109116903e08f2578f91bf9b15fad002b3",
          "md5": "8d7e003aa85ceb1a668cda18e88a1aba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "0.2.00"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        }
      ],
      "files": [
        {
          "name": "tpac-0.4.00.jar",
          "url": "tpac-0.4.00.jar",
          "size": 174673,
          "sha512": "64f5a5c638fd61acac78ca086d687a8b192a54dbd51735cf9289eb3c4a843dae8616132304773d52b1eddedb16ac905b50bf229412a132309415034edecba2c0",
          "sha256": "09e09a4ed987561e50fbb5fb6f0591ea950d51691bdeeb844fe15524e09b7163",
          "sha1": "a53d05109116903e08f2578f91bf9b15fad002b3",
          "md5": "8d7e003aa85ceb1a668cda18e88a1aba"
        }
      ]
    }
  ]
}
