{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "tpac",
    "version": "0.4.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "upwmqhjvyrcmvgl5ad7xzwiqee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tpac-0.4.00.jar",
          "url": "tpac-0.4.00.jar",
          "size": 172034,
          "sha512": "f2731d96d0af98be3ef8044fc32429b1a47f3a38ed3bed874501953c54ed6218b3f25934d935ca6048e7cdd1489c136cdb44b88d0c5788f9d0c36bdf72d4af22",
          "sha256": "903ab05d0365ef146851b67d7399211ef343a559a23067c6eb56e226147af564",
          "sha1": "286197bf886ca60717be1c3ca5f0c792eeeae4d7",
          "md5": "da96c6d08fed557f9fbde9f6676baa62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "0.2.00"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        }
      ],
      "files": [
        {
          "name": "tpac-0.4.00.jar",
          "url": "tpac-0.4.00.jar",
          "size": 172034,
          "sha512": "f2731d96d0af98be3ef8044fc32429b1a47f3a38ed3bed874501953c54ed6218b3f25934d935ca6048e7cdd1489c136cdb44b88d0c5788f9d0c36bdf72d4af22",
          "sha256": "903ab05d0365ef146851b67d7399211ef343a559a23067c6eb56e226147af564",
          "sha1": "286197bf886ca60717be1c3ca5f0c792eeeae4d7",
          "md5": "da96c6d08fed557f9fbde9f6676baa62"
        }
      ]
    }
  ]
}
