{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "tpac",
    "version": "0.4.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "exmrmodg7jf6djvn4ddfeji5mi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tpac-0.4.00.jar",
          "url": "tpac-0.4.00.jar",
          "size": 176633,
          "sha512": "eece6febb2b82e47314d006c8261751591763a22d5aaa5ea943ccb355bd478673544f1abb841218de2137536319a5cbf46a9db0b27aa7b65c767394fde1afc73",
          "sha256": "349039404ff7567873d4a60b8af70d8c1e2054be7ab1c5e41d42d04d6af12b9f",
          "sha1": "eaf05545f8696bc520d12bd436c61c46733ccf96",
          "md5": "b148fb6863561546b946010988045e1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "0.2.00"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        }
      ],
      "files": [
        {
          "name": "tpac-0.4.00.jar",
          "url": "tpac-0.4.00.jar",
          "size": 176633,
          "sha512": "eece6febb2b82e47314d006c8261751591763a22d5aaa5ea943ccb355bd478673544f1abb841218de2137536319a5cbf46a9db0b27aa7b65c767394fde1afc73",
          "sha256": "349039404ff7567873d4a60b8af70d8c1e2054be7ab1c5e41d42d04d6af12b9f",
          "sha1": "eaf05545f8696bc520d12bd436c61c46733ccf96",
          "md5": "b148fb6863561546b946010988045e1a"
        }
      ]
    }
  ]
}
