{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "bltxt",
    "version": "0.3.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "wv6jq7rd5rgwtbtd3avvya6o7i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bltxt-0.3.00.jar",
          "url": "bltxt-0.3.00.jar",
          "size": 107409,
          "sha512": "bb2d9c2174a97e715eddd05b63353584eb6a4aa94c21f0d6ab9659d9ce3b9ea56bd7bbdcb09cf83a4647018cd0ce7774e4c9d18461233b075bc2c733feb7a228",
          "sha256": "8e840e01d905ef5b742f6215324be6a765a3a7d335765e5c55604ff6930c8bda",
          "sha1": "a5e9a32d07c4f0a74263f23163a0744479e9e25a",
          "md5": "bbd7ceb82d4da4a01abe4442b9e9573b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "0.2.00"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        }
      ],
      "files": [
        {
          "name": "bltxt-0.3.00.jar",
          "url": "bltxt-0.3.00.jar",
          "size": 107409,
          "sha512": "bb2d9c2174a97e715eddd05b63353584eb6a4aa94c21f0d6ab9659d9ce3b9ea56bd7bbdcb09cf83a4647018cd0ce7774e4c9d18461233b075bc2c733feb7a228",
          "sha256": "8e840e01d905ef5b742f6215324be6a765a3a7d335765e5c55604ff6930c8bda",
          "sha1": "a5e9a32d07c4f0a74263f23163a0744479e9e25a",
          "md5": "bbd7ceb82d4da4a01abe4442b9e9573b"
        }
      ]
    }
  ]
}
