{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "clmap",
    "version": "0.3.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "cabrbvoqlvd2zixkzvpscy3kki"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "clmap-0.3.00.jar",
          "url": "clmap-0.3.00.jar",
          "size": 53573,
          "sha512": "56e323c8fdd9a82a0e15630ee1f5c18e5b84020069b44527f98611fd2a1e8e1364aa72bbf41094baa84b18fb149094ddc33807dc623d0f7b401476a739911e34",
          "sha256": "f2f5b9598cd3dd4ea04c1acb32ec60644b5cbf5da9913b0adb6568b632015af3",
          "sha1": "4b4602c15744dcb7d9dba3d86600c0afb16f6e88",
          "md5": "1044b93f35b2b1ff9d411aad520d8763"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "0.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "0.4.00"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        }
      ],
      "files": [
        {
          "name": "clmap-0.3.00.jar",
          "url": "clmap-0.3.00.jar",
          "size": 53573,
          "sha512": "56e323c8fdd9a82a0e15630ee1f5c18e5b84020069b44527f98611fd2a1e8e1364aa72bbf41094baa84b18fb149094ddc33807dc623d0f7b401476a739911e34",
          "sha256": "f2f5b9598cd3dd4ea04c1acb32ec60644b5cbf5da9913b0adb6568b632015af3",
          "sha1": "4b4602c15744dcb7d9dba3d86600c0afb16f6e88",
          "md5": "1044b93f35b2b1ff9d411aad520d8763"
        }
      ]
    }
  ]
}
