{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "bltxt",
    "version": "0.3.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "wrsueg75zndqfj4nk2ar63chiu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bltxt-0.3.00.jar",
          "url": "bltxt-0.3.00.jar",
          "size": 107360,
          "sha512": "f71b7fa16f0a171b9f2c2488e5d08b22aecd84aa21c5fcedb3bc62a19e636171088bf09af2f10f2577fcce7ac547d3a95b9132ff3e466c741f40b48cb3c2c380",
          "sha256": "0e0f4b3b41337d77a135ce373f5785b723c31a1eb57572872e2170c3b4a82cdf",
          "sha1": "dc3bbd08a75adc4550ae654e47f21111dec8b907",
          "md5": "6e90351021fa45c35c5190835ebb59e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "0.2.00"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.5.10"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        }
      ],
      "files": [
        {
          "name": "bltxt-0.3.00.jar",
          "url": "bltxt-0.3.00.jar",
          "size": 107360,
          "sha512": "f71b7fa16f0a171b9f2c2488e5d08b22aecd84aa21c5fcedb3bc62a19e636171088bf09af2f10f2577fcce7ac547d3a95b9132ff3e466c741f40b48cb3c2c380",
          "sha256": "0e0f4b3b41337d77a135ce373f5785b723c31a1eb57572872e2170c3b4a82cdf",
          "sha1": "dc3bbd08a75adc4550ae654e47f21111dec8b907",
          "md5": "6e90351021fa45c35c5190835ebb59e6"
        }
      ]
    }
  ]
}
