{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "switem",
    "version": "1.2.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "1.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "switem-1.2.00.jar",
          "url": "switem-1.2.00.jar",
          "size": 104161,
          "sha512": "1848cffd6716ec738b1957e2d04ed6f977265f8b74442c677351f522d569bc7ef5aecb490cf692ceb215499dc233a2640889472409252dbacb2dbdfb325fb856",
          "sha256": "ba52e2cbc92ac4de96ad2e7e7bb1e15a1479fc17a139e8a2b28e6dd378ec502b",
          "sha1": "6faab9d64b9f3992fd0c9d007b116daf16da3eb8",
          "md5": "c890deb8169fccb814159e27265c8b3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "1.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "switem-1.2.00.jar",
          "url": "switem-1.2.00.jar",
          "size": 104161,
          "sha512": "1848cffd6716ec738b1957e2d04ed6f977265f8b74442c677351f522d569bc7ef5aecb490cf692ceb215499dc233a2640889472409252dbacb2dbdfb325fb856",
          "sha256": "ba52e2cbc92ac4de96ad2e7e7bb1e15a1479fc17a139e8a2b28e6dd378ec502b",
          "sha1": "6faab9d64b9f3992fd0c9d007b116daf16da3eb8",
          "md5": "c890deb8169fccb814159e27265c8b3d"
        }
      ]
    }
  ]
}
