{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "switem",
    "version": "1.2.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "1.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "switem-1.2.00.jar",
          "url": "switem-1.2.00.jar",
          "size": 104170,
          "sha512": "0892bef83a71263f52c3f8e17066ce603ffe108a42b50ffe4e346ec9ab815293b631296095bcdcaf339dcc7d700c796526f2877a874f7723e2807690a0346be6",
          "sha256": "309f2348aab19b8a6b4cd8c5310b7ed3de1157c0627c0d5763f499e7d6e6c94e",
          "sha1": "aba9136d7e4afff9cf4b4a2cc9fa7f5b039f57eb",
          "md5": "e9eef5b463e49b5b8df312e084c34031"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "1.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "switem-1.2.00.jar",
          "url": "switem-1.2.00.jar",
          "size": 104170,
          "sha512": "0892bef83a71263f52c3f8e17066ce603ffe108a42b50ffe4e346ec9ab815293b631296095bcdcaf339dcc7d700c796526f2877a874f7723e2807690a0346be6",
          "sha256": "309f2348aab19b8a6b4cd8c5310b7ed3de1157c0627c0d5763f499e7d6e6c94e",
          "sha1": "aba9136d7e4afff9cf4b4a2cc9fa7f5b039f57eb",
          "md5": "e9eef5b463e49b5b8df312e084c34031"
        }
      ]
    }
  ]
}
