{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "switem",
    "version": "1.2.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "1.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "switem-1.2.00.jar",
          "url": "switem-1.2.00.jar",
          "size": 103995,
          "sha512": "d9c2df8fdf34ec88bde87a813f5cb47057b3dd36f6ee2dc3ae384e57a1b523ec60844daeab776e7f60cbd1b8e5e3fabc6c445e8d9b8557fae04151840c955eea",
          "sha256": "5fac26acb53963cc30b637207dfcba820b0f6ce791f6de0f28ec940046ae6244",
          "sha1": "6673cfc210490b208be97b0750417fef13cfb3cb",
          "md5": "46ac9679a4798fec0074518b6ab77cde"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "1.2.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "switem-1.2.00.jar",
          "url": "switem-1.2.00.jar",
          "size": 103995,
          "sha512": "d9c2df8fdf34ec88bde87a813f5cb47057b3dd36f6ee2dc3ae384e57a1b523ec60844daeab776e7f60cbd1b8e5e3fabc6c445e8d9b8557fae04151840c955eea",
          "sha256": "5fac26acb53963cc30b637207dfcba820b0f6ce791f6de0f28ec940046ae6244",
          "sha1": "6673cfc210490b208be97b0750417fef13cfb3cb",
          "md5": "46ac9679a4798fec0074518b6ab77cde"
        }
      ]
    }
  ]
}
