{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.longfish801",
    "module": "switem",
    "version": "1.3.00",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "2.0.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "switem-1.3.00.jar",
          "url": "switem-1.3.00.jar",
          "size": 104162,
          "sha512": "ae97485bc9a91ed9e86d5bb32d9ac6092cc990400c499bcd71a65405d18d573c335e330824f8ca58f8c17080655492a5b98866245d140d849343b28f54b21920",
          "sha256": "e1ab719d86bee48fd55b63fdb7598e006ef215f406e33a2d28725318cf843093",
          "sha1": "4f0b214d273a0557e385efc2483fb66666ad4c04",
          "md5": "ac68bf40211f38c626c6bcaa9b4ee8e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "clmap",
          "version": {
            "requires": "2.0.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "gonfig",
          "version": {
            "requires": "1.1.00"
          }
        },
        {
          "group": "io.github.longfish801",
          "module": "tpac",
          "version": {
            "requires": "1.2.00"
          }
        }
      ],
      "files": [
        {
          "name": "switem-1.3.00.jar",
          "url": "switem-1.3.00.jar",
          "size": 104162,
          "sha512": "ae97485bc9a91ed9e86d5bb32d9ac6092cc990400c499bcd71a65405d18d573c335e330824f8ca58f8c17080655492a5b98866245d140d849343b28f54b21920",
          "sha256": "e1ab719d86bee48fd55b63fdb7598e006ef215f406e33a2d28725318cf843093",
          "sha1": "4f0b214d273a0557e385efc2483fb66666ad4c04",
          "md5": "ac68bf40211f38c626c6bcaa9b4ee8e0"
        }
      ]
    }
  ]
}
